apiVersion: batch/v1
kind: Job
metadata:
  name: iozone-job
#  namespace: IV
spec:
  completions: 1
  template:
    metadata:	  
      name: iozone-job
    spec:
      containers:
      - name: iozone
        image: ranada/iozone:latest
        imagePullPolicy: Always
        env:
        - name: TEST_END_TIME
          value: "__TEST_END_TIME__"
        - name: IOZONE_TEST_DIR
          value: "__IOZONE_TEST_DIR__"
        - name: MOUNT_DEVICE
          value: "__MOUNT_DEVICE__"
        - name: ELASTICSEARCH_HOST
          value: "__ELASTICSEARCH_HOST__"
        - name: ELASTICSEARCH_USER
          value: "__ELASTICSEARCH_USER__"
        - name: ELASTICSEARCH_PASSWORD
          value: "__ELASTICSEARCH_PASSWORD__"
        - name: STAY_ALIVE_SLEEP_TIME
          value: "__STAY_ALIVE_SLEEP_TIME__"
#      imagePullSecrets:
#        - name: yard
      restartPolicy: Never
