apiVersion: batch/v1
kind: Job
metadata:
  name: block-storage-job
  namespace: meadowgate
spec:
  completions: 1
  template:
    metadata:	  
      name: block-storage-job
    spec:
      volumes:
#      - name: scp-secret
#        secret:
#          secretName: "scp-secret"
      - name: block-storage-data-volume
        persistentVolumeClaim: 
          claimName: block-storage-pvc-ceph
    
      containers:
      - name: block-storage
        image: ranada/block-storage-test:latest
        imagePullPolicy: Always
        env:
        - name: FILE_SIZES
          value: "__FILE_SIZES__"
        - name: TEST_END_TIME
          value: "__TEST_END_TIME__"
        - name: ELASTICSEARCH_HOST
          value: "__ELASTICSEARCH_HOST__"
        - name: ELASTICSEARCH_USER
          value: "__ELASTICSEARCH_USER__"
        - name: ELASTICSEARCH_PASSWORD
          value: "__ELASTICSEARCH_PASSWORD__"
        - name: STAY_ALIVE_SLEEP_TIME
          value: "__STAY_ALIVE_SLEEP_TIME__"
        volumeMounts:
#       - name: scp-secret
#          mountPath: /home/block-storage
#          readOnly: true
        - name: block-storage-data-volume
          mountPath: "/data"
      restartPolicy: Never
