apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iozone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: iozone
    spec:
      containers:
        - image: ranada/iozone:latest
          name: iozone
          env:
          - name: TEST_END_TIME
            value: "__TEST_END_TIME__"
          - name: IOZONE_TEST_DIR
            value: "__IOZONE_TEST_DIR__"
          - name: MOUNT_DEVICE
            value: "__MOUNT_DEVICE__"
          - name: ELASTICSEARCH_HOST
            value: "__ELASTICSEARCH_HOST__"
          - name: ELASTICSEARCH_USER
            value: "__ELASTICSEARCH_USER__"
          - name: ELASTICSEARCH_PASSWORD
            value: "__ELASTICSEARCH_PASSWORD__"
          - name: STAY_ALIVE_SLEEP_TIME
            value: "__STAY_ALIVE_SLEEP_TIME__"
